apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo2
  name: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo2
    spec:
      containers:
      - image: app-test:v1
        name: app-test
        resources: {}
status: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo2
  name: demo2
spec:
  ports:
  - name: 8084-8080
    port: 8084
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo2
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo2
  name: demo2
spec:
  ports:
  - name: 8084-8080
    port: 8084
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo2
  type: ClusterIP
status:
  loadBalancer: {}
